home:
    path: /
    defaults: { _controller: AppBundle:Default:index }

patient_creation:
    path: /patient/new
    defaults: { _controller: AppBundle:Patient:new }

login:
    path: /login
    defaults: { _controller: AppBundle:Login:login }

logout:
    path: /logout